/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollPollIdIndexRouteImport } from './routes/poll/$pollId/index'
import { Route as PollPollIdPreviewRouteImport } from './routes/poll/$pollId/preview'
import { Route as PollPollIdLayoutRouteImport } from './routes/poll/$pollId/_layout'

const PollPollIdRouteImport = createFileRoute('/poll/$pollId')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdRoute = PollPollIdRouteImport.update({
  id: '/poll/$pollId',
  path: '/poll/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdIndexRoute = PollPollIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PollPollIdRoute,
} as any)
const PollPollIdPreviewRoute = PollPollIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => PollPollIdRoute,
} as any)
const PollPollIdLayoutRoute = PollPollIdLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PollPollIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poll/$pollId': typeof PollPollIdLayoutRoute
  '/poll/$pollId/preview': typeof PollPollIdPreviewRoute
  '/poll/$pollId/': typeof PollPollIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poll/$pollId': typeof PollPollIdIndexRoute
  '/poll/$pollId/preview': typeof PollPollIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poll/$pollId': typeof PollPollIdRouteWithChildren
  '/poll/$pollId/_layout': typeof PollPollIdLayoutRoute
  '/poll/$pollId/preview': typeof PollPollIdPreviewRoute
  '/poll/$pollId/': typeof PollPollIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/poll/$pollId' | '/poll/$pollId/preview' | '/poll/$pollId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/poll/$pollId' | '/poll/$pollId/preview'
  id:
    | '__root__'
    | '/'
    | '/poll/$pollId'
    | '/poll/$pollId/_layout'
    | '/poll/$pollId/preview'
    | '/poll/$pollId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PollPollIdRoute: typeof PollPollIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId': {
      id: '/poll/$pollId'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId'
      preLoaderRoute: typeof PollPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId/': {
      id: '/poll/$pollId/'
      path: '/'
      fullPath: '/poll/$pollId/'
      preLoaderRoute: typeof PollPollIdIndexRouteImport
      parentRoute: typeof PollPollIdRoute
    }
    '/poll/$pollId/preview': {
      id: '/poll/$pollId/preview'
      path: '/preview'
      fullPath: '/poll/$pollId/preview'
      preLoaderRoute: typeof PollPollIdPreviewRouteImport
      parentRoute: typeof PollPollIdRoute
    }
    '/poll/$pollId/_layout': {
      id: '/poll/$pollId/_layout'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId'
      preLoaderRoute: typeof PollPollIdLayoutRouteImport
      parentRoute: typeof PollPollIdRoute
    }
  }
}

interface PollPollIdRouteChildren {
  PollPollIdLayoutRoute: typeof PollPollIdLayoutRoute
  PollPollIdPreviewRoute: typeof PollPollIdPreviewRoute
  PollPollIdIndexRoute: typeof PollPollIdIndexRoute
}

const PollPollIdRouteChildren: PollPollIdRouteChildren = {
  PollPollIdLayoutRoute: PollPollIdLayoutRoute,
  PollPollIdPreviewRoute: PollPollIdPreviewRoute,
  PollPollIdIndexRoute: PollPollIdIndexRoute,
}

const PollPollIdRouteWithChildren = PollPollIdRoute._addFileChildren(
  PollPollIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PollPollIdRoute: PollPollIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
