/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PollsImport } from './routes/polls'
import { Route as IndexImport } from './routes/index'
import { Route as PollPollIdImport } from './routes/poll/$pollId'

// Create/Update Routes

const PollsRoute = PollsImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PollPollIdRoute = PollPollIdImport.update({
  id: '/poll/$pollId',
  path: '/poll/$pollId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsImport
      parentRoute: typeof rootRoute
    }
    '/poll/$pollId': {
      id: '/poll/$pollId'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId'
      preLoaderRoute: typeof PollPollIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/polls': typeof PollsRoute
  '/poll/$pollId': typeof PollPollIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/polls': typeof PollsRoute
  '/poll/$pollId': typeof PollPollIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/polls': typeof PollsRoute
  '/poll/$pollId': typeof PollPollIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/polls' | '/poll/$pollId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/polls' | '/poll/$pollId'
  id: '__root__' | '/' | '/polls' | '/poll/$pollId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PollsRoute: typeof PollsRoute
  PollPollIdRoute: typeof PollPollIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PollsRoute: PollsRoute,
  PollPollIdRoute: PollPollIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/polls",
        "/poll/$pollId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/polls": {
      "filePath": "polls.tsx"
    },
    "/poll/$pollId": {
      "filePath": "poll/$pollId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
